modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="rayon-particle"
version="${version}"
displayName="Rayon Particle API"
logoFile="icon.png"
credits="Lazurite team who made original Rayon Particle"
authors="The Lazurite Team"
description="A physics API for Forge."
[[dependencies.rayon]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rayon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.4.0,)"
    ordering="NONE"
    side="BOTH"

# {
#   "schemaVersion": 1,
#   "id": "rayon-particle",
#   "version": "${version}",
#   "name": "Rayon Particle API",
#   "description": "The particle API for Rayon.",
#   "authors": [ "The Lazurite Team" ],
#   "license": "MIT",
#   "environment": "*",
#   "icon": "icon.png",
#   "mixins": [ "rayon-particle.mixins.json" ],
#
#   "entrypoints": {
#     "client": [
#       "dev.lazurite.rayon.particle.impl.RayonParticle"
#     ]
#   },
#
#   "depends": {
#     "minecraft": "1.18.x",
#     "fabricloader": ">=0.11",
#     "fabric-api-base": "*"
#   },
#
#   "contact": {
#     "homepage": "https://lazurite.dev",
#     "sources": "https://github.com/lazuritemc/Rayon",
#     "issues": "https://github.com/LazuriteMC/Rayon/issues"
#   },
#
#   "custom": {
#     "modmenu": {
#       "links": { "modmenu.discord": "https://discord.gg/NNPPHN7b3P" },
#       "badges": [ "library" ],
#       "parent": "rayon"
#     }
#   }
# }
