modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="testmod_particle"
version="${version}"
displayName="Testmod particle"
logoFile="icon.png"
credits="Lazurite team who made original Rayon"
authors="The Lazurite Team"
description="A physics API for Forge."
[[dependencies.testmod_particle]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.testmod_particle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.testmod_particle]]
    modId="rayon_particle"
    mandatory=true
    versionRange="[1.4.0,)"
    ordering="NONE"
    side="BOTH"


# {
#   "schemaVersion": 1,
#   "id": "testmod_particle",
#   "version": "${version}",
#   "license": "MIT",
#   "environment": "*",
#   "entrypoints": {},
#
#   "depends": {
#     "minecraft": "1.18.x",
#     "fabricloader": ">=0.11",
#     "fabric": "*",
#     "rayon-particle": "*"
#   }
# }
