modLoader = "javafml"
loaderVersion = "[38,)"
license = "MIT"

[[mods]]
modId = "rayon_test"
version = "${version}"
displayName = "Rayon Test"
authors = "Lazurite Team"

[[dependencies.rayon_test]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rayon_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"